/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef tcoin_CONSTANTS_H
#define tcoin_CONSTANTS_H

#include "tcoin_types.h"

namespace tcoin { namespace v2 {

class tcoinConstants {
 public:
  tcoinConstants();

};

extern const tcoinConstants g_tcoin_constants;

}} // namespace

#endif
