/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "tcoin_constants.h"

namespace tcoin { namespace v2 {

const tcoinConstants g_tcoin_constants;

tcoinConstants::tcoinConstants() {
}

}} // namespace

